version: "3"
services:
  insurance:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: localhost:5000/tony/insurance
    network_mode: host
    environment:
      db_user: ${db_user}
      db_password: ${db_password}
      db_url: ${db_url}
      db_port: ${db_port}
      db_name: ${db_name}
      server_port: ${server_port}
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    network_mode: host
    environment:
      - POSTGRES_DB=insurance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
